### ISSUE TITLE
OSX scripts for starting container

### ISSUE THREAD

**Issue by stnava** [dorianps/docker#1]
Simple change --- just switch `xdg-open` to `open` .... a "nice to have" request for OS X users.

You might just use a variable:

```
myopen=xdg-open
if [[ `uname` == "Darwin" ]] ; then 
  myopen=open
fi
```

Thanks for this - works well - and happy 2020!

**Comment by dorianps** [comment]
Thanks for the tip. I added your recommendation. You can try the script again if it works on Mac. Happy new year. :)
