### ISSUE TITLE
advice for installation on another ubuntu docker

### ISSUE THREAD

**Issue by alenauus** [dorianps/docker#3]
Hi Dorian,

Thank you for implementing this docker! It is very useful.

I just wanted to ask you for a quick advice. 
We've been trying to install an itksnap executable to another docker (already existing MIRTK-based pipeline and it will include itksnap) - but while it works on ubuntu - there are issues on Windows. 

We get this error (after trying to load a .nii file) for qt5 itksnap: 
The X11 connection broke: I/O error (code 1)
XIO: fatal IO error 22 (Invalid argument) on X server "host.docker.internal:0.0"

It runs without errors with qt4 - but the display is wrong. 

This is how we run the docker image:
docker run --env DISPLAY="host.docker.internal:0.0" --rm -it -v C:\Users\Tomo\Desktop\docker-tests:/home/mydata --ipc="host" --privileged fetalsvrtk/svrtk:dcm_dev_v2

Do you know what might be causing this error?

Thank you.

Best wishes,
Alena

**Comment by dorianps** [comment]
The qt5 does not work I think, I use the qt4 version as you see [here](https://github.com/dorianps/docker/blob/master/itksnap/Dockerfile.itksnap#L26). So can't help with qt5, maybe @pyushkevich
 knows more.

Honestly, I am seeing issues also in plain Windows with the display (no docker involved). Last night I saw displaced axes  when putting to full screen, and updating to the latest nightly itksnap did not help. Have not reported it yet, but it made me think of the display issues you mention with qt4.

**Comment by alenauus** [comment]
Thank you : )

Yes, it worked with qt4 and after removing "Native opengl" setting in the X program that we used.

I guess that there are just too many versions of everything these days..

Best wishes,
Alena
